version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-avar_dictionary}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["/app/docker/entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /var/www/avar/static:/app/staticfiles
    ports:
      - "8000:8000"

volumes:
  postgres_data:
