# Generated by Django 5.2.4 on 2025-07-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=40)),
                ("ip_address", models.GenericIPAddressField()),
                ("date", models.DateField()),
                ("last_activity", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["last_activity"], name="website_vis_last_ac_1b8029_idx"
                    ),
                    models.Index(fields=["date"], name="website_vis_date_eeefe3_idx"),
                ],
                "unique_together": {("session_key", "date")},
            },
        ),
    ]
