# Generated by Django 5.2.4 on 2025-10-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="О проекте", max_length=256, verbose_name="Заголовок"
                    ),
                ),
                ("content", models.TextField(verbose_name="Описание")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменено"),
                ),
            ],
            options={
                "verbose_name": "Информация о проекте",
                "verbose_name_plural": "Информация о проекте",
            },
        ),
    ]
